# apiVersion: v1
# items:
# - allowVolumeExpansion: true
#   apiVersion: storage.k8s.io/v1
#   kind: StorageClass
#   metadata:
#     annotations:
#       meta.helm.sh/release-name: nfs-subdir-external-provisioner
#       meta.helm.sh/release-namespace: storage
#     creationTimestamp: "2023-08-22T10:41:18Z"
#     labels:
#       app: nfs-subdir-external-provisioner
#       app.kubernetes.io/managed-by: Helm
#       chart: nfs-subdir-external-provisioner-4.0.18
#       heritage: Helm
#       release: nfs-subdir-external-provisioner
#     name: nfs-client
#     resourceVersion: "872052"
#     uid: 6b5b19e6-bce6-40b3-a9ea-c2ec6eecebe1
#   parameters:
#     archiveOnDelete: "true"
#   provisioner: cluster.local/nfs-subdir-external-provisioner
#   reclaimPolicy: Delete
#   volumeBindingMode: Immediate


kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: demo-claim
  namespace: storage
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi