################################
### Service Accounts
################################

apiVersion: v1
kind: ServiceAccount
metadata:
  name: myuser
  namespace: default

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvviewer
  namespace: default 

################################
### Secrets 
################################

# apiVersion: v1
# kind: Secret
# metadata:
#   name: kubernetes-dashboard-csrf
#   namespace: default

# type: Opaque
# data:
#   csrf: ""