apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default 
  name: R-RWD
rules:
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete", "create"]
