kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: RB-RWD
  namespace: default 
subjects:
- kind: Group
  name: operation
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: R-RWD
  apiGroup: rbac.authorization.k8s.io
